name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:

  linux:
    runs-on: ubuntu-latest
    steps:
    - name: Install Eigen3
      run: sudo apt install libeigen3-dev
    - name: Install OpenBLAS
      run: sudo apt install libopenblas-dev
    - name: Install GTest
      run: sudo apt install libgtest-dev
    - name: Install Vc
      run: sudo apt install vc-dev
    - uses: actions/checkout@v2
    - uses: actions/setup-python@v2
      with:
        python-version: '3.x'
    - name: Install Meson/Ninja
      run: |
        pip install meson ninja
    - name: Meson Setup
      run: meson setup build
      env:
        CC: gcc
        CXX: g++
    - name: Run tests
      run: meson test -C build -v --num-processes 1
    - uses: actions/upload-artifact@v2
      if: failure()
      with:
        name: Linux_Meson_Testlog
        path: build/meson-logs/testlog.txt
